name: CI

on:
    pull_request:
        branches: ['*']
    push:
        branches: [main]
    merge_group:
    workflow_dispatch:

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v6

            - name: Setup pnpm
              uses: pnpm/action-setup@v5
              with:
                  cache: true

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: lts/*

            - name: Install deps
              run: pnpm install

            - name: Check format
              run: pnpm format:check

            - name: Run eslint
              run: pnpm lint

            - name: Run typecheck
              run: pnpm typecheck

            - name: Run build
              run: pnpm build

            - name: Run tests
              run: pnpm test
