name: Release

on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

permissions:
    id-token: write # Required for OIDC
    contents: write

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v5
              with:
                  cache: true

            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                  node-version: lts/*
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: pnpm install

            - name: Run build
              run: pnpm build

              # We make sure ci is passing before releasing
            - name: Wait for CI to finish
              uses: lewagon/wait-on-check-action@v1.7.0
              if: github.event_name == 'push'
              with:
                  ref: ${{ github.ref }}
                  check-name: ci
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  verbose: true
                  wait-interval: 8

            - name: Create release
              run: pnpm publish --no-git-checks

            - run: pnpx changelogithub
              if: always() && github.event_name == 'push'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
